Repository TDD-ToyProjectDrivenDevelopers/Financial-Ledger-Spring, pull requests merged in 2022-07, with the labels that each got.

#4 모든 프로젝트 엔티티 클래스 추가
  .gitignore
  src/main/java/gubun/financialledger/FinancialLedgerApplication.java
  src/main/java/gubun/financialledger/account/Account.java
  src/main/java/gubun/financialledger/bank/Bank.java
  src/main/java/gubun/financialledger/category/Category.java
  src/main/java/gubun/financialledger/category/DefaultCategoryType.java
  src/main/java/gubun/financialledger/common/BaseEntity.java
  src/main/java/gubun/financialledger/common/TXHistoryCategory.java
  src/main/java/gubun/financialledger/diary/Diary.java
  src/main/java/gubun/financialledger/txhistory/TXHistory.java
  src/main/java/gubun/financialledger/txhistory/TXType.java
  src/main/java/gubun/financialledger/user/User.java
  src/main/java/gubun/financialledger/user/UserRole.java
  src/main/resources/application.yml
Labels: enhancement, help wanted

#6 부트스트랩 세팅 및 WebConfig 파일 생성
  src/main/java/gubun/financialledger/config/WebConfig.java
  src/main/java/gubun/financialledger/config/WebSecurityConfig.java
  src/main/resources/static/css/style.css
  src/main/resources/static/css/style.css.map
  src/main/resources/static/images/logo.png
  src/main/resources/static/js/contact.js
  src/main/resources/static/js/script.js
  src/main/resources/static/plugins/animated-text/animated-text.css
  src/main/resources/static/plugins/animated-text/animated-text.js
  src/main/resources/static/plugins/aos/aos.css
  src/main/resources/static/plugins/aos/aos.js
  src/main/resources/static/plugins/bootstrap/bootstrap.min.css
  src/main/resources/static/plugins/bootstrap/bootstrap.min.js
  src/main/resources/static/plugins/counto/animate.css
  src/main/resources/static/plugins/counto/apear.js
  src/main/resources/static/plugins/counto/counTo.js
  src/main/resources/static/plugins/fontawesome/css/all.css
  src/main/resources/static/plugins/fontawesome/webfonts/fa-brands-400.eot
  src/main/resources/static/plugins/fontawesome/webfonts/fa-brands-400.svg
  src/main/resources/static/plugins/fontawesome/webfonts/fa-brands-400.ttf
  src/main/resources/static/plugins/fontawesome/webfonts/fa-brands-400.woff
  src/main/resources/static/plugins/fontawesome/webfonts/fa-brands-400.woff2
  src/main/resources/static/plugins/fontawesome/webfonts/fa-regular-400.eot
  src/main/resources/static/plugins/fontawesome/webfonts/fa-regular-400.svg
  src/main/resources/static/plugins/fontawesome/webfonts/fa-regular-400.ttf
  src/main/resources/static/plugins/fontawesome/webfonts/fa-regular-400.woff
  src/main/resources/static/plugins/fontawesome/webfonts/fa-regular-400.woff2
  src/main/resources/static/plugins/fontawesome/webfonts/fa-solid-900.eot
  src/main/resources/static/plugins/fontawesome/webfonts/fa-solid-900.svg
  src/main/resources/static/plugins/fontawesome/webfonts/fa-solid-900.ttf
  src/main/resources/static/plugins/fontawesome/webfonts/fa-solid-900.woff
  src/main/resources/static/plugins/fontawesome/webfonts/fa-solid-900.woff2
  src/main/resources/static/plugins/google-map/map.js
  src/main/resources/static/plugins/jQuery/jquery.min.js
  src/main/resources/static/plugins/magnific-popup/jquery.magnific-popup.js
  src/main/resources/static/plugins/magnific-popup/jquery.magnific-popup.min.js
  src/main/resources/static/plugins/magnific-popup/magnific-popup.css
  src/main/resources/static/plugins/owl-carousel/owl.carousel.min.css
  src/main/resources/static/plugins/owl-carousel/owl.carousel.min.js
  src/main/resources/static/plugins/owl-carousel/owl.theme.default.min.css
  src/main/resources/static/plugins/shuffle/shuffle.min.js
  src/main/resources/static/plugins/themify/css/themify-icons.css
  src/main/resources/static/plugins/themify/fonts/themify.eot
  src/main/resources/static/plugins/themify/fonts/themify.svg
  src/main/resources/static/plugins/themify/fonts/themify.ttf
  src/main/resources/static/plugins/themify/fonts/themify.woff
  src/main/resources/templates/blog-grid.html
  src/main/resources/templates/blog-sidebar.html
  src/main/resources/templates/blog-single.html
  src/main/resources/templates/contact.html
  src/main/resources/templates/home.html
  src/main/resources/templates/index.html
Labels: enhancement

#10 프로젝트 구조 변경 기능별구조 + 계층별구조
  src/main/java/gubun/financialledger/account/entity/Account.java
  src/main/java/gubun/financialledger/bank/entity/Bank.java
  src/main/java/gubun/financialledger/category/entity/Category.java
  src/main/java/gubun/financialledger/category/type/DefaultCategoryType.java
  src/main/java/gubun/financialledger/common/config/WebConfig.java
  src/main/java/gubun/financialledger/common/config/WebSecurityConfig.java
  src/main/java/gubun/financialledger/common/entity/BaseEntity.java
  src/main/java/gubun/financialledger/common/entity/TXHistoryCategory.java
  src/main/java/gubun/financialledger/common/exception/GlobalExceptionController.java
  src/main/java/gubun/financialledger/common/util/CommonUtil.java
  src/main/java/gubun/financialledger/diary/entity/Diary.java
  src/main/java/gubun/financialledger/txhistory/entity/TXHistory.java
  src/main/java/gubun/financialledger/txhistory/type/TXType.java
  src/main/java/gubun/financialledger/user/entity/User.java
  src/main/java/gubun/financialledger/user/entity/UserRole.java
  src/main/java/gubun/financialledger/user/repository/UserRepository.java
  src/main/java/gubun/financialledger/user/service/CustomUserDetailService.java
Labels: enhancement

#14 기본 회원가입 기능 추가
  src/main/java/gubun/financialledger/common/config/WebSecurityConfig.java
  src/main/java/gubun/financialledger/user/PrincipalDetails.java
  src/main/java/gubun/financialledger/user/auth/PrincipalDetailsService.java
  src/main/java/gubun/financialledger/user/controller/RegistrationController.java
  src/main/java/gubun/financialledger/user/controller/UserController.java
  src/main/java/gubun/financialledger/user/dto/RegistrationForm.java
  src/main/java/gubun/financialledger/user/entity/User.java
  src/main/java/gubun/financialledger/user/repository/UserRepository.java
  src/main/java/gubun/financialledger/user/service/CustomUserDetailService.java
  src/main/java/gubun/financialledger/user/service/UserService.java
  src/main/resources/static/css/error/style.css
  src/main/resources/templates/register.html
Labels: help wanted

#17 AWS RDS(PostgreSQL), S3 개발 환경 세팅
  build.gradle
  src/main/java/gubun/financialledger/common/config/JasyptConfig.java
  src/main/java/gubun/financialledger/user/entity/User.java
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: enhancement

#18 기본 로그인 구현
  src/main/java/gubun/financialledger/common/config/WebSecurityConfig.java
  src/main/java/gubun/financialledger/user/PrincipalDetails.java
  src/main/java/gubun/financialledger/user/auth/CustomAuthenticationFailureHandler.java
  src/main/java/gubun/financialledger/user/auth/PrincipalDetailsService.java
  src/main/resources/static/js/login/login.js
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
Labels: bug, help wanted

#21 OAuth 2.0 - kakao login 기능 추가
  build.gradle
  src/main/java/gubun/financialledger/common/config/WebSecurityConfig.java
  src/main/java/gubun/financialledger/user/PrincipalDetails.java
  src/main/java/gubun/financialledger/user/entity/User.java
  src/main/java/gubun/financialledger/user/oauth/PrincipalOauth2UserService.java
  src/main/java/gubun/financialledger/user/oauth/provider/KakaoUserInfo.java
  src/main/java/gubun/financialledger/user/oauth/provider/OAuth2UserInfo.java
  src/main/resources/application-dev.yml
  src/main/resources/static/images/google_login_button.png
  src/main/resources/static/images/kakao_login_button.png
  src/main/resources/templates/login.html
Labels: enhancement, help wanted

#23 ImageUploader 구현
  build.gradle
  src/main/java/gubun/financialledger/common/config/AWSS3Config.java
  src/main/java/gubun/financialledger/common/util/ImageUploader.java
  src/main/java/gubun/financialledger/common/util/LocalImageUploader.java
  src/main/java/gubun/financialledger/common/util/S3ImageUploader.java
  src/main/java/gubun/financialledger/diary/entity/controller/ImageController.java
  src/main/java/gubun/financialledger/user/TestUser.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/templates/index.html
  src/main/resources/templates/upload-form.html
Labels: enhancement

#26 Develop to Feature/googleLogin branch
  build.gradle
  src/main/java/gubun/financialledger/common/config/AWSS3Config.java
  src/main/java/gubun/financialledger/common/util/ImageUploader.java
  src/main/java/gubun/financialledger/common/util/LocalImageUploader.java
  src/main/java/gubun/financialledger/common/util/S3ImageUploader.java
  src/main/java/gubun/financialledger/diary/entity/controller/ImageController.java
  src/main/java/gubun/financialledger/user/TestUser.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/templates/index.html
  src/main/resources/templates/upload-form.html
Labels: bug

#27 이메일 인증 로직 구현
  build.gradle
  src/main/java/gubun/financialledger/common/config/WebSecurityConfig.java
  src/main/java/gubun/financialledger/user/auth/MailHandler.java
  src/main/java/gubun/financialledger/user/controller/RegistrationController.java
  src/main/java/gubun/financialledger/user/dto/RegistrationForm.java
  src/main/java/gubun/financialledger/user/service/MailService.java
  src/main/resources/application-dev.yml
  src/main/resources/static/css/error/style.css
  src/main/resources/static/js/register/email.js
  src/main/resources/static/js/register/validation.js
  src/main/resources/templates/register.html
Labels: help wanted

#28 아이디/비밀번호 찾기 구현
  src/main/java/gubun/financialledger/common/config/WebConfig.java
  src/main/java/gubun/financialledger/common/config/WebSecurityConfig.java
  src/main/java/gubun/financialledger/user/controller/IdInquiryController.java
  src/main/java/gubun/financialledger/user/controller/PwInquiryController.java
  src/main/java/gubun/financialledger/user/dto/IdInquiryForm.java
  src/main/java/gubun/financialledger/user/dto/PwInquiryForm.java
  src/main/java/gubun/financialledger/user/entity/User.java
  src/main/java/gubun/financialledger/user/repository/UserRepository.java
  src/main/java/gubun/financialledger/user/service/MailProperties.java
  src/main/java/gubun/financialledger/user/service/MailService.java
  src/main/java/gubun/financialledger/user/service/UserService.java
  src/main/resources/static/js/pwInquiry/email.js
  src/main/resources/static/js/pwInquiry/validation.js
  src/main/resources/templates/404.html
  src/main/resources/templates/blank.html
  src/main/resources/templates/buttons.html
  src/main/resources/templates/cards.html
  src/main/resources/templates/charts.html
  src/main/resources/templates/idInquiry.html
  src/main/resources/templates/pwInquiry.html
  src/main/resources/templates/register.html
  src/main/resources/templates/tables.html
  src/main/resources/templates/utilities-animation.html
  src/main/resources/templates/utilities-border.html
  src/main/resources/templates/utilities-color.html
  src/main/resources/templates/utilities-other.html
Labels: help wanted

#30 인증, 인가 관련 리팩토링 완료
  src/main/java/gubun/financialledger/FinancialLedgerApplication.java
  src/main/java/gubun/financialledger/common/config/WebSecurityConfig.java
  src/main/java/gubun/financialledger/diary/entity/controller/ImageController.java
  src/main/java/gubun/financialledger/user/TestUser.java
  src/main/java/gubun/financialledger/user/auth/PrincipalDetails.java
  src/main/java/gubun/financialledger/user/auth/PrincipalDetailsService.java
  src/main/java/gubun/financialledger/user/controller/IdInquiryController.java
  src/main/java/gubun/financialledger/user/controller/InquiryController.java
  src/main/java/gubun/financialledger/user/controller/MailController.java
  src/main/java/gubun/financialledger/user/controller/PwInquiryController.java
  src/main/java/gubun/financialledger/user/controller/RegistrationController.java
  src/main/java/gubun/financialledger/user/handler/CustomAuthenticationFailureHandler.java
  src/main/java/gubun/financialledger/user/handler/MailHandler.java
  src/main/java/gubun/financialledger/user/oauth/PrincipalOauth2UserService.java
  src/main/java/gubun/financialledger/user/repository/UserRepository.java
  src/main/java/gubun/financialledger/user/service/MailService.java
  src/main/resources/static/js/pwInquiry/email.js
  src/main/resources/static/js/register/email.js
  src/main/resources/templates/idInquiry.html
  src/main/resources/templates/login.html
  src/main/resources/templates/pwInquiry.html
  src/main/resources/templates/register.html
Labels: help wanted

#33 OAuth 2.0 - google login 기능 추가
  src/main/java/gubun/financialledger/user/oauth/PrincipalOauth2UserService.java
  src/main/java/gubun/financialledger/user/oauth/provider/GoogleUserInfo.java
  src/main/resources/application-dev.yml
  src/main/resources/static/css/login.css
  src/main/resources/static/images/google_login_btn.png
  src/main/resources/static/images/google_login_button.png
  src/main/resources/templates/login.html
Labels: enhancement, help wanted
